#
# pacman.conf for Pochota Web
#

[options]
HoldPkg     = pacman glibc
Architecture = x86_64
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
