#
# pacman.conf for Pochota Web (includes chaotic-aur for brave-bin)
#

[options]
HoldPkg     = pacman glibc
Architecture = x86_64
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[chaotic-aur]
SigLevel = Never
Server = https://cdn-mirror.chaotic.cx/chaotic-aur/aur/x86_64
